Remove scalapack for now
It would appear conda compilers are unable to build scalapac.

Linux PETSc log:

```pre
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: $PREFIX/lib/libgfortran.so.4: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
            SCALAPACK: Downloaded DirPath not found.. skipping: $PREFIX/petsc/lib64
```

Mac PETSc log:

```pre
Undefined symbols for architecture x86_64:
  "__gfortran_st_write", referenced from:
      _pxerbla_ in libscalapack.a(pxerbla.o)
  "__gfortran_st_write_done", referenced from:
      _pxerbla_ in libscalapack.a(pxerbla.o)
  "__gfortran_transfer_character_write", referenced from:
      _pxerbla_ in libscalapack.a(pxerbla.o)
  "__gfortran_transfer_integer_write", referenced from:
      _pxerbla_ in libscalapack.a(pxerbla.o)
ld: symbol(s) not found for architecture x86_64
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
            SCALAPACK: Downloaded DirPath not found.. skipping: $PREFIX/petsc/lib64
```

Removing scalapack support from PETSc build.

Refs #21